### ISSUE TITLE
seafile client syncs .git/ even if listed in seafile-ignore.txt

### ISSUE THREAD

**Issue by rmmonster** [haiwen/seafile#1137]
I have a seafile library which looks like this:

`~/Something`

This folder is also under version control by git so there are

`~/Something/.git`
and
`~/Something/.gitignore`

I couldn't figure out a string which would stop the seafile client form syncing .git when the git repo is initialized by `git init`

What I currently have in my seafile-ignore.txt 

```*~
.*
.*/
*/.*
*.git/*
*.git/
.git/*
.git*
.git/
```

I'm aware that the `seafile-ignore.txt` is only used when new files and folder are created on the client side. Even if I remove the `.git` files and folders and wait for the *cloud* to sync and then re-init the git repo it's files and folders are added again.

What irritated me most is that `.gitignore` is ignored by seafile.

**Comment by shoeper** [comment]
.gitignore is afaik blocked by your rules.
Have you read http://seafile.com/en/help/ignore/.

**Comment by forouher** [comment]
is your seafile-ignore.txt in the root of the repository?

**Comment by sjentzsch** [comment]
I have the same issue: Excluding a directory which is a git repository does *not* work, the content is successfully ignored, but I cannot prevent seafile from always syncing the raw folder and its .git-folder ...

**Comment by rongmu** [comment]
Similar problem here.
I want to ignore the R Studio project folder `.Rproj.user`, so I added the line below to the `seafile-ignore.txt` in my library root.
```
.Rproj.user/
```
Sadly it never works.

**Comment by rmmonster** [comment]
I just started a new Seafile folder and retried the whole `seafile-ignore.txt` thing.
I created the new folder and added it to seafile. I then added some files. The files where synced. I then added a `seafile-ignore.txt` with `.git/` as only content.
I then initialized a git repo in the "root" seafile folder. It instantly synced.

I revisited this issue to see if anything changed and saw that @rongmu has a similar issue with another .dot folder so I tried adding `.something/` to the `seafile-ingore.txt`. Then I created the folder and added a file with content into it. It wasn't synced.

I initially thought this was just some trivial parsing error in the `seafile-ignore.txt` but it seems there is more to it.

Right now I'm running seafile 4.1.6 from the AUR (https://aur.archlinux.org/packages/seafile-client/) on an up-to-date archlinux.

@shoeper yes I read the `seafile-ignore.txt` help
@forouher yes the `seafile-ignore.txt` is in the "root" of the seafile folder.

**Comment by Burtan** [comment]
I can confirm this problem. 

Server, Debian Jessie with Seafile 4.2.2
Client, Debian Stretch with Seafile 4.2.2

When ignoring a whole folder, subfolder with .git folders do get synced nevertheless.

**Comment by hville** [comment]
Looks like the parser doesn't like expressions that starts with a `.` dot
try `*.startswithadot/` or `?startswithadot/` and `*/.startswithadot/`

**Comment by rmmonster** [comment]
@hville your fix doesn't work for me.

moved .git out of the seafile library
seafile removed .git from seafile library
added ?git to seafileignore
moved .git back to seafile library 
seafile syncs .git to the library

seafile client 4.2.6

**Comment by hville** [comment]
Sorry it did not work for you.
This is what I have:

myLib/seafile-ignore.txt:
?git/
.git/
*/.git/


good luck,
Hugo.

Hugo
+60 12 4997551 (KL)

**Comment by mkollaro** [comment]
The pattern `?folder/` to ignore `.folder/` seems to work for me, at least for the windows client.

**Comment by killing** [comment]
The current client version fails to ignore folders. The result is that the folders are synced, but the files inside the folders are ignored. This will be fixed in the next client update. And this error only happens after a client restart.

**Comment by fedmich** [comment]
I'm also having problems with seafile-ignore.txt
I'm trying to exclude *.ldb (Microsoft Access databases lock file)

It keeps popping and saying the file was Added or Modified
I'm using Seafile client 4.3.0 in Windows with Server in Windows 7 too

**Comment by freeplant** [comment]
The problem is fixed in v4.3.2.

**Comment by fedmich** [comment]
The problem is still not fixed.

I upgraded client to 4.3.2 both laptop and desktop and i'm still getting those .ldb files getting synced over.
![seafile sync err](https://cloud.githubusercontent.com/assets/497509/9423343/992bb194-48f2-11e5-81c1-b981ae95c2a2.png)

**Comment by shoeper** [comment]
Have you deleted those from your library before adding the rules?

https://www.seafile.com/en/help/ignore/

**Comment by fedmich** [comment]
Yup, I've tried a lot of things already.
1. Deleted it
2. Resync lib
3. Even remove directory and re-adding a new library

**Comment by escoreal** [comment]
Works for me now with Seafile Client 4.3.3 and the following "seafile-ignore.txt":
.git/*
.git*

Thanks!
