### ISSUE TITLE
Upon system resume, seafile-applet does not connect anymore; race-condition.

### ISSUE THREAD

**Issue by deragon** [haiwen/seafile#1274]
On Linux Ubuntu 14.04 LTS Trusty thar, client version 4.1.6, 64 bits, whenever a system resumes from suspend, seafile-applet seams to try to connect to the server before the Wifi signal is established.  After failing, it remains in the failing state despite the Wifi connection coming up seconds later.

The workaround is to quit the applet and restart it.

Seafile should nicely retry once in a while to establish connection.  Maybe for the first minute, retry at every 5s, then once each minute for 5 minutes, then every 5 minutes.

The ${HOME}/.ccnet/logs/applet.log shows a serious problem with re-connection, with the last message repeating multiple times per seconds, for ever and ever.

[2015-06-06 12:28:05][MessageListener] connected to daemon
[2015-06-06 12:28:11]Unable to get config (int) value download_limit
[2015-06-06 12:28:11]Unable to get config (int) value upload_limit
[2015-06-06 12:28:11]The latest version is 4.1.3
[system suspends and resume here]
[2015-06-06 12:43:11][Sea RPC] Bad response: 515 peer down.
[2015-06-06 12:43:11][api] network error for http://voxel001.deragon.biz:8000/api2/unseen_messages/: Network unreachable
[2015-06-06 12:43:11][api] network error for http://voxel001.deragon.biz:8000/api2/ping/: Network unreachable
[2015-06-06 12:43:11][Sea RPC] Bad response: 102 processor is dead.
[2015-06-06 12:43:11][Sea RPC] Bad response: 102 processor is dead.
[2015-06-06 12:43:11][Sea RPC] Bad response: 102 processor is dead.
[2015-06-06 12:43:11][Sea RPC] Bad response: 102 processor is dead.
[2015-06-06 12:43:11][Sea RPC] Bad response: 102 processor is dead.
[... this never stops; always the same error multiple times per seconds ...]

**Comment by killing** [comment]
4.2 client should have fixed the issue.

2015-06-07 2:00 GMT+08:00 Hans Deragon <notifications@github.com>:

**Comment by deragon** [comment]
Wow, that was a fast response.  Thank you.  Were you already aware of this problem or you just looked into the code to find out where the problem was?

When is 4.2 expected?

**Comment by killing** [comment]
4.2 is already out. See our website:-)

2015-06-07 21:24 GMT+08:00 Hans Deragon <notifications@github.com>:

**Comment by deragon** [comment]
Ok, this is confusing.  I never notice that there exist two client versions.  I used the first one, which latest is 4.1.6.  http://seafile.com/en/download/

Before I install the version with Shibboleth, why are there two client versions?  I cannot find the answer on the web.  Ideally, there should only be one with all the features, or if one feature is annoying and requires its own release, then both clients should be of the same version, only with different feature sets.

**Comment by deragon** [comment]
I installed seafile-client 4.2.3 and server 4.2.2, and now it is worse.  Same problem but now even if the network is up!  No workaround applies anymore; nothing syncs from my laptop.  I tested the four ports and they are all responding.

However, on my server, the local seafile-client can talk to the local seafile server without a problem.  Why is my laptop client behaving differently than on my server?

Can I add some debugging traces?  BTW, why is it reporting <code>The latest version is 4.1.3</code>?

<pre>
[2015-06-10 03:53:17]starting ccnet:  ("-c", "/sp/home/hans/.ccnet")
[2015-06-10 03:53:18]trying to connect to ccnet daemon...
[2015-06-10 03:53:18]connected to ccnet daemon
[2015-06-10 03:53:18]starting seaf-daemon:  ("-c", "/sp/home/hans/.ccnet", "-d", "/sp/home/hans/.seafile-data", "-w", "/sp/home/hans")
[2015-06-10 03:53:18]seafile daemon is now running
[2015-06-10 03:53:18][Rpc Client] connected to daemon
[2015-06-10 03:53:18][MessageListener] connected to daemon
[2015-06-10 03:53:20]Unable to get config (int) value download_limit
[2015-06-10 03:53:20]Unable to get config (int) value upload_limit
[2015-06-10 03:53:21][Rpc Client] connected to daemon
[2015-06-10 03:53:21]The latest version is 4.1.3
[2015-06-10 03:53:38][Sea RPC] Bad response: 515 peer down.
[2015-06-10 03:53:38][Sea RPC] Bad response: 102 processor is dead.
[2015-06-10 03:53:38][Sea RPC] Bad response: 102 processor is dead.
[2015-06-10 03:53:38][Sea RPC] Bad response: 102 processor is dead.
[2015-06-10 03:53:38][Sea RPC] Bad response: 102 processor is dead.
[... line always repeated ...]
</pre>

**Comment by shoeper** [comment]
Have you setup http://manual.seafile.com/deploy/deploy_http_sync.html?

Have you run the upgrade scripts as described here: http://manual.seafile.com/deploy/upgrade.html?

**Comment by deragon** [comment]
I do not use any web server, thus no https.  Port 8082 is accessible.  Yes, I upgraded properly the database and it was successful.

The applet just crashed and apport generated a 60M crash file.  Can this be useful for anybody?

**Comment by killing** [comment]
What can you see in the seafile.log of the client? Click on the tray icon and choose open log folder.
Are you sure it's the seafile-applet crashes? Does the try icon disappear after the crash?

**Comment by deragon** [comment]
One of seafile-client compenent, seaf-daemon, crashed, but only once.  The crash name is:  _usr_bin_seaf-daemon.1000.crash.  Unfortunately, I deleted the log file after the crash, because they were becoming huge.  Sorry about that.

I upgraded to 4.2.4.  But I just realized that my URL for my account is http://<server>:8000.  Is this right?  Through a browser, the URL works just fine.  How can I instruct the client to use port 8082?   http://<server>:8082 shows 'If you see this page, Seafile HTTP syncing component works.'. so the server works fine.  Beside, seafile-client 4.2.3 on my server, running seafile-cli works just fine.

I think my configuration is ok.  I just notice that before all icons turn into orange clouds, for an instance at startup, some are green.  Then it all fails.  Connection reset (104).  But it used to work with 4.1.6 a few days ago and I have no problem connecting to my server with other applications such as ssh and http.

But for the sake of argument, lets assume my network has a problem.  Why can't the applet create a new connection and retry a few times?  I do not see that in the logs.

applet.log:
<pre>
[2015-06-11 05:15:04][MessageListener] connected to daemon
[2015-06-11 05:15:06]Unable to get config (int) value download_limit
[2015-06-11 05:15:06]Unable to get config (int) value upload_limit
[2015-06-11 05:15:06][Rpc Client] connected to daemon
[2015-06-11 05:15:07]The latest version is 4.1.3
[2015-06-11 05:15:23][Sea RPC] Bad response: 515 peer down.
[2015-06-11 05:15:23][Sea RPC] Bad response: 102 processor is dead.
...
</pre>

ccnet.log
<pre>
[06/11/15 05:15:06] ../common/session.c(375): Accepted a local client
[06/11/15 05:15:23] ../common/peer.c(943): Local peer down
[06/11/15 05:15:23] ../common/peer.c(941): libevent got an error! what=33, errno=104 (Connection reset by peer)
[06/11/15 05:15:23] ../common/peer.c(943): Local peer down
[06/11/15 05:15:23] ../common/peer.c(943): Local peer down
</pre>

**Comment by deragon** [comment]
Reverted to 4.1.6.  It now works again.  Sort of eliminate the possibility that the problem is the network.

**Comment by deragon** [comment]
So, is there anything that can be done?  Eventually I would need to move away from 4.1.6.  Would you have a 4.2.4 version with debugging symbols and more traces I could run?  There is a bug in the 4.2.* series and I doubt that I will be the only one affected.

**Comment by killing** [comment]
Can you post your applet.log and seafile.log here? Judging from the
phenomenon only usually can't reveal the real problem.

2015-06-17 23:02 GMT+08:00 Hans Deragon <notifications@github.com>:

**Comment by deragon** [comment]
Found something interesting in seafile.log.  Seams that there is a problem with the server 4.2.2.  Note that the server was restarted multiple time, so restarting it does not help.

Following are the logs when I started, then gracefully ended the applet.  Note though that on the client computer, the seaf-daemon daemon crashed.

seafile.log:
<pre>
[06/20/15 06:56:38] seaf-daemon.c(504): starting seafile client 4.2.4
[06/20/15 06:56:38] seaf-daemon.c(506): seafile source code version daa8107c2e51a92e769a2fa0f43e892be90aed63
[06/20/15 06:56:38] ../common/mq-mgr.c(60): [mq client] mq cilent is started
[06/20/15 06:56:39] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seafile.heartbeat
[06/20/15 06:57:21] http-tx-mgr.c(1026): Bad response code for GET http://voxel001.deragon.biz:8000/seafhttp/protocol-version: 404.
[06/20/15 06:57:22] sync-mgr.c(656): Repo 'media' sync state transition from 'synchronized' to 'uploading'.
[06/20/15 06:57:22] http-tx-mgr.c(2646): Upload with HTTP sync protocol version 1.
[06/20/15 06:57:22] http-tx-mgr.c(926): Transfer repo '07b0df09': ('normal', 'init') --> ('normal', 'check')
[06/20/15 06:57:22] sync-mgr.c(656): Repo 'Software' sync state transition from 'synchronized' to 'committing'.
[06/20/15 06:57:22] http-tx-mgr.c(1367): Parse response failed: '[' or '{' expected near 'If'.
[06/20/15 06:57:22] ../common/fs-mgr.c(1308): Dirent name not set for dir object e0d108de1aa8edcc352a2360942c280187ee8f17.
[06/20/15 06:57:22] ../common/diff-simple.c(236): Failed to find dir e0d108de1aa8edcc352a2360942c280187ee8f17.
[06/20/15 06:57:22] http-tx-mgr.c(1811): Failed to diff local and master head for repo 07b0df09.
[06/20/15 06:57:22] http-tx-mgr.c(2655): Failed to calculate upload size delta for repo 07b0df09-13bf-49f6-beeb-85e049f96e2d.
[06/20/15 06:57:22] http-tx-mgr.c(926): Transfer repo '07b0df09': ('normal', 'check') --> ('error', 'finished')
[06/20/15 06:57:22] sync-mgr.c(724): Repo 'media' sync state transition from uploading to 'error': 'Error occured in upload.'.
</pre>

applet.log
<pre>
[2015-06-20 06:56:37]starting ccnet:  ("-c", "/sp/home/hans/.ccnet") 
[2015-06-20 06:56:38]trying to connect to ccnet daemon...
[2015-06-20 06:56:38]connected to ccnet daemon
[2015-06-20 06:56:38]starting seaf-daemon:  ("-c", "/sp/home/hans/.ccnet", "-d", "/sp/home/hans/.seafile-data", "-w", "/sp/home/hans") 
[2015-06-20 06:56:38]seafile daemon is now running
[2015-06-20 06:56:38][Rpc Client] connected to daemon
[2015-06-20 06:56:38][MessageListener] connected to daemon
[2015-06-20 06:57:20]Unable to get config (int) value download_limit
[2015-06-20 06:57:20]Unable to get config (int) value upload_limit
[2015-06-20 06:57:20][Rpc Client] connected to daemon
[2015-06-20 06:57:21]The latest version is 4.1.3
[2015-06-20 06:57:26][Sea RPC] Bad response: 515 peer down.
[2015-06-20 06:57:26][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:27][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:28][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:29][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:30][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:31][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:32][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:33][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:34][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:35][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:36][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:37][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:38][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:39][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:40][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:41][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:42][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:43][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:44][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:45][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:46][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:47][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:48][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:49][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:50][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:51][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:52][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:53][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:54][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:55][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:56][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:57][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:58][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:57:59][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:00][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:01][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:02][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:03][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:04][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:05][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:06][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:07][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:08][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:09][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:10][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:11][Sea RPC] Bad response: 102 processor is dead.
[2015-06-20 06:58:12][Daemon Mgr] stopping ccnet/seafile daemon
</pre>

**Comment by killing** [comment]
Here is a debug package: https://seacloud.cc/f/93a9de7fcb/
It ships with debug symbols, so once the seaf-daemon crashes you can get a coredump.

To enable core dump on Ubuntu

```
ulimit -c unlimited
echo "core.%p" | sudo tee /proc/sys/kernel/core_pattern
```

To debug the problem, you have run seafile manually without the GUI.

```
ccnet -c ~/.ccnet
seaf-daemon -c ~/.ccnet -d <path_to_seafile_folder>/.seafile-data -w <path_to_seafile_folder>
```

Note that you should run the above command on the same terminal as you run ulimit.

After the daemon crashes, there should be a core.pid file in the current directory. You can compress the core and send it to me. Or if you have privacy concern, just use gdb to print the back trace.

```
gdb /usr/bin/seaf-daemon core.pid
bt
```

Thanks for helping.

**Comment by deragon** [comment]
`<path_to_seafile_folder>` is ambiguous  for me.  I have `${HOME}/.seafile-data`, as defined in my `${HOME}/.ccnet/seafile.ini`.  I know I can follow the `-d` parameter with that value.  However, what is the definition of `<path_to_seafile_folder>` on the client?  What do I actually put following the `-w <worktree_dir>`?

**Comment by killing** [comment]
path_to_seafile_folder means the folder you chose for Seafile when you
first run the client. There is dialog to let you choose the default folder
to put the synced libraries. It's the same as "worktree_dir".

2015-06-21 19:08 GMT+08:00 Hans Deragon <notifications@github.com>:

**Comment by deragon** [comment]
This is odd.  No core.pid created.
<pre>
[hans@demloka .ccnet] seaf-daemon -c /sp/home/hans/.ccnet -d /sp/home/hans/.seafile-data -w /sp/home/hans
Segmentation fault
[hans@demloka .ccnet] cat /proc/sys/kernel/core_pattern
core.%p
[hans@demloka .ccnet] ls -l core*
/bin/ls: cannot access core*: No such file or directory
</pre>
For what is worth, here is the output of `strace`:
<pre>
access("/sp/home/hans/.seafile-data/repo.db-wal", F_OK) = -1 ENOENT (No such file or directory)
fstat(14, {st_mode=S_IFREG|0644, st_size=37888, ...}) = 0
fcntl(14, F_SETLK, {type=F_UNLCK, whence=SEEK_SET, start=0, len=0}) = 0
read(15, "t\3160\352\v~\347\242N\366\236`\226\2\224\362", 16) = 16
gettid()                                = 10251
write(5, "\1\4\0\270\0\0\3\352300\n0 019441398356988fd4"..., 192) = 192
epoll_wait(6, {{EPOLLIN, {u32=30, u64=30}}}, 32, 999) = 1
epoll_ctl(6, EPOLL_CTL_DEL, 30, {EPOLLIN, {u32=30, u64=30}}) = 0
read(30, "a", 1)                        = 1
close(30)                               = 0
close(31)                               = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3477, ...}) = 0
write(3, "[06/23/15 00:51:54] http-tx-mgr."..., 112) = 112
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3477, ...}) = 0
write(3, "[06/23/15 00:51:54] sync-mgr.c(7"..., 127) = 127
epoll_wait(6, {{EPOLLIN, {u32=5, u64=5}}}, 32, 980) = 1
ioctl(5, FIONREAD, [15])                = 0
read(5, "\1\3\0\7\0\0\3\352200 OK\n", 15) = 15
epoll_wait(6, {{EPOLLIN, {u32=27, u64=27}}}, 32, 980) = 1
epoll_ctl(6, EPOLL_CTL_DEL, 27, {EPOLLIN, {u32=27, u64=27}}) = 0
read(27, "a", 1)                        = 1
close(27)                               = 0
close(28)                               = 0
epoll_wait(6,  <unfinished ...>
+++ killed by SIGSEGV +++
Segmentation fault
</pre>

**Comment by killing** [comment]
Please try this new package out: https://seacloud.cc/f/93a9de7fcb/
It should fix the crash problem.

**Comment by deragon** [comment]
No more crash.  Great and thanks for the quick turn around!  Now the original problem still persists despite using client 4.2.4, i.e. seafile-applet fails to connect after resume from suspend.  The fix does not work in my case.

**Comment by deragon** [comment]
Tried with client 4.2.8 and the problem persists.

**Comment by killing** [comment]
The fix will be released in 4.3 version. For now you can try this test
package: https://seacloud.cc/f/e9d3e4e45a/?raw=1
Some other user has confirmed that it fixes the problem.

2015-07-19 19:05 GMT+08:00 Hans Deragon <notifications@github.com>:

**Comment by deragon** [comment]
Thanks, but do you have a preview version for Linux?  The one you are providing is for Mac.  I run Ubuntu 14.04 LTS x86_64.

**Comment by deragon** [comment]
Tried with client 4.3.1 and the problem persists.

**Comment by deragon** [comment]
Any chance to get this fix?  Still occurring with 4.4.0 client and 4.4.3 server.

**Comment by torrentkino** [comment]
Hello killing,

I have the same problem. I use Debian/Sid. Is this issue related to this thread?
> https://forum.seafile-server.org/t/sync-error-sea-rpc-bad-response-102-processor-is-dead/3431

The thread deals with the seaf-daemon that is linked against two versions of libcrypto:
> ldd `which seaf-daemon` | grep libcrypto
> libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fe98aed8000)
> libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007fe98721d000)

Kind regards,
Aiko

**Comment by torrentkino** [comment]
I have deleted _.ccnet_ and _.seafile-data_. That seems to fix my primary issues. No more:
> Bad response: 102 processor is dead.

Kind regards,
Aiko Barz
