### ISSUE TITLE
upgrading Pro from 4.4.7 to 5.0.2 causes clinet to detect broken repos

### ISSUE THREAD

**Issue by qnxor** [haiwen/seafile#1485]
As reported here by two users: https://forum.seafile-server.org/t/seafile-pro-server-5-0-2-is-finally-ready-a-stable-release/3617/15

Upgraded using the standard method. I'm using SQLite. Everything seemed fine on the server but the clients report:

    [12/23/15 12:30:12] sync-mgr.c(728): Repo 'Dec' sync state transition from initializing to 'error': 'Repo is damaged on relay.'.

Downgraded to 4.4.7 and it works fine again.

**Comment by freeplant** [comment]
It is solved in pro v5.0.3.

**Comment by qnxor** [comment]
Well, it's not fixed. I get this when running the upgrade script:

Performing upgrade ...

-------------------------------------------------------------
This script would upgrade your seafile server from 4.4 to 5.0
Press [ENTER] to contiune
-------------------------------------------------------------



Updating seafile/seahub database ...
```
[INFO] You are using SQLite3
[INFO] updating seahub database...
Traceback (most recent call last):
  File "/seafile/server/seafile-pro-server-5.0.3/upgrade/db_update_helper.py", line 349, in <module>
    main()
  File "/seafile/server/seafile-pro-server-5.0.3/upgrade/db_update_helper.py", line 344, in main
    db_updater.update_db()
  File "/seafile/server/seafile-pro-server-5.0.3/upgrade/db_update_helper.py", line 245, in update_db
    super(SQLiteDBUpdater, self).update_db()
  File "/seafile/server/seafile-pro-server-5.0.3/upgrade/db_update_helper.py", line 117, in update_db
    self.update_seahub_sql(seahub_sql)
  File "/seafile/server/seafile-pro-server-5.0.3/upgrade/db_update_helper.py", line 269, in update_seahub_sql
    self.apply_sqls(self.seahub_db, sql_path)
  File "/seafile/server/seafile-pro-server-5.0.3/upgrade/db_update_helper.py", line 259, in apply_sqls
    conn.execute(line)
sqlite3.OperationalError: duplicate column name: login_id

Failed to upgrade your database
```

**Comment by qnxor** [comment]
That's because I previously attempted to upgrade from 4.4.7 to 5.0.2 which executed `upgrade/sql/5.0.0/sqlite3/seahub.sql`

	CREATE TABLE IF NOT EXISTS "constance_config" (
	    "id" integer NOT NULL PRIMARY KEY,
	    "key" varchar(255) NOT NULL UNIQUE,
	    "value" text NOT NULL
	);

	ALTER TABLE "profile_profile" ADD COLUMN "login_id" varchar(225);
	ALTER TABLE "profile_profile" ADD COLUMN "contact_email" varchar(225);
	ALTER TABLE "profile_profile" ADD COLUMN "institution" varchar(225);

	CREATE UNIQUE INDEX "profile_profile_1b43c217" ON "profile_profile" ("login_id");
	CREATE INDEX "profile_profile_3b46cb17" ON "profile_profile" ("contact_email");
	CREATE INDEX "profile_profile_71bbc151" ON "profile_profile" ("institution");

I'm not the only user in this situation so it would be safer if you checked for the existence of the `login_id`, `contact_email` and `institution` before attempting to add them and their indexes

**Comment by qnxor** [comment]
I commented out the lines:

	--ALTER TABLE "profile_profile" ADD COLUMN "login_id" varchar(225);
	--ALTER TABLE "profile_profile" ADD COLUMN "contact_email" varchar(225);
	--ALTER TABLE "profile_profile" ADD COLUMN "institution" varchar(225);

	--CREATE UNIQUE INDEX "profile_profile_1b43c217" ON "profile_profile" ("login_id");
	--CREATE INDEX "profile_profile_3b46cb17" ON "profile_profile" ("contact_email");
	--CREATE INDEX "profile_profile_71bbc151" ON "profile_profile" ("institution");

Then I rerun `upgrade_4.4_5.0.sh` and got more errors:

	‘/seafile/server/ccnet/ccnet.conf’ -> ‘/seafile/server/conf/’
	cp: cannot create regular file ‘/seafile/server/conf/’: Not a directory
	‘/seafile/server/seafile-data/seafile.conf’ -> ‘/seafile/server/conf/’
	cp: cannot create regular file ‘/seafile/server/conf/’: Not a directory
	‘/seafile/server/seahub_settings.py’ -> ‘/seafile/server/conf/’
	cp: cannot create regular file ‘/seafile/server/conf/’: Not a directory
	‘/seafile/server/pro-data/seafevents.conf’ -> ‘/seafile/server/conf/’
	cp: cannot create regular file ‘/seafile/server/conf/’: Not a directory

For some reason the `conf` folder was missing! Also, the upgrade script renamed all my conf files even though the copy with `cp` failed ... I had to all these steps manually as well.

The upgrade script seems a bit sloppy because it does things or leaves things in a crippled state even though previous operations fail. This then require manual work and close inspection.

If I may suggest some improvements, you could first do the operations on a copy of the files/database (instead of the real ones) and only commit everything if all operations are successful. This includes SQL operations and file copy/rename/deletions. That way the upgrade can be reverted safely.
