### ISSUE TITLE
Client can't resolve host name through socks5 proxy

### ISSUE THREAD

**Issue by atom-42** [haiwen/seafile#1520]
I have a seafile server running behind a TOR hidden service (and it works great).

My client (v5.0.3 linux, got from arch linux user repository), cannot synchronize files with the onion server. My seafile.log file fills with these :
"[01/21/16 08:26:23] http-tx-mgr.c(701): libcurl failed to GET http://azertyuiopqsdfgh.onion:8000/seafhttp/protocol-version: Couldn't resolve host name.
[01/21/16 08:26:23] http-tx-mgr.c(701): libcurl failed to GET http://azertyuiopqsdfgh.onion:8082/protocol-version: Couldn't resolve host name."

But as soon as i run a socat TCP/SOCKS tunnel between 127.0.0.1 and azertyuiopqsdfgh.onion for port 8000 and 8082, and then make seafile-client point to 127.0.0.1, everything works well.

I think that, in the first case, seafile-client dosen't try to resole the server's host name through the given proxy, so it isn't able to find any *.onion. In the second case, hostname resolution is handled by socat which uses the given socks5 proxy to resolve the hostname. In this case, seafile-client doesn't have any host name resolution to do so everything works fine.

A possible solution would be to let the user decide if he wants to resolve the server's host name through th proxy, or not.

**Comment by NZSmartie** [comment]
I'm having a similar issue. 
I host a private Seafile server where the host name only resolves on my local network's DNS server. When I set up a socks5 proxy into my home network and configure Seafile client on Windows to use the socks5 proxy, It claims it's connected to the server. but the folder has the error message "Cannot resolve server address".

1. To reproduce this issue. set up seafile on a network where the DNS will resolve the hostname for that network.
1. From Windows. create a Socks5 proxy to the local network
  a. ssh example `ssh user@myjumphost.com -D 8123` (I'm using bash for windows)
  b. PuTTY can do the same with Dynamic Port forwarding
1. Configure Seafile to use the proxy 
  a. server: `127.0.0.1`
  b. port: `8123`
1. Observe that the client will connect to the server, but fail to sync with already configured folders.

**Comment by lins05** [comment]
FWIW https://unix.stackexchange.com/a/175891/136391

cc @killing

**Comment by grolongo** [comment]
Hi, I'm having exact same problem as @atom-42.

Configuration:
  - Seafile Server 6.2.2 on Raspbian, running behind a Tor Hidden Service
  - Seafile Client 6.1.3 on macOS and Windows

After adding the socks5 proxy in Seafile Network Settings, the client is capable of receiving the list of libraries but can't sync any file.

Looking at `~/.ccnet/logs/seafile.log` I get the same errors as OP, the log file being filled with hostname resolving issues when using an .onion address.

So yes, I think Seafile misses to resolve the hostname specified in the server address through the given proxy settings.

One solution for now given by someone on the forum (I think that's what OP suggested too): https://forum.seafile.com/t/seafile-proxy-hostname-resolving/2756

Using SSH with ProxyCommand to tunnel a port forwarding into Tor makes Seafile sync files normally, even though it feels like a labyrinth.

Would it be possible to have this option in `~/.ccnet/ccnet.conf` ? Or even better in the GUI with the proxy settings?

Regards.

**Comment by NZSmartie** [comment]
Why was this closed? This issue is still present in the most recent version so seafile client and seadrive

**Comment by killing** [comment]
OK. Sorry for mistakenly closing it. Now I find that it's a bug in the code. We'll fix it in later version.

**Comment by killing** [comment]
This should be fixed with 8.0.1 version. Please have a try.

**Comment by RichLuna** [comment]
Sorry, I'm still seeing this bug.

OS: Linux Mint 20.1 x86_64 
Seafile Client 8.0.1

**Comment by nzkarit** [comment]
This bug is still present in: Seafile Client 8.0.5
