### ISSUE TITLE
the Seafile client could not initialize

### ISSUE THREAD

**Issue by LeDistordu** [haiwen/seafile#2146]
Hi,

I have 4 workstations under Windows 10 with the same problem. No problem with version 6.1.x, but when you migrate to 6.2.9, it does not work! Seafile does not boot. If I create a new blank windows session, the seafile client works perfectly. This is not a solution, we do not want to remake all sessions.

We tried lots of things, uninstalling, reinstalling, removing all references to seafile on disk, ...

Can you help me ?

![seafile-applet_2018-12-20_12-11-21](https://user-images.githubusercontent.com/7805145/50284360-1f957600-0459-11e9-8e0c-11f756fff07b.jpg)

**Comment by LeDistordu** [comment]
UP ?

**Comment by marcusmysc** [comment]
We had the same problem with several PCs 

I already sent a mail to the Seafile support but they didn't find anything in the logs and can't reproduce it.

**Comment by killing** [comment]
Do you have anti virus software that may block the communication between the Seafile GUI and the seafile sync daemon? The new version of client removes the 'ccnet' component. In old version, a TCP connection is used for communication between GUI - ccnet - seafile. With the new version, a named pipe is used from GUI - seafile.

You could try to trust Seafile application in your anti virus software.

**Comment by StanislawSchwarz** [comment]
Same problem here, but I found a workaround you start/install seafile when the window disappear you open a second seaf-demon.exe and it manage to initialize the client.
I have two system: notebook works, the pc doesnt, both windows 10 same build and update level, both windows defender.

**Comment by marcusmysc** [comment]
Fixed with 6.2.11

**Comment by SolidBrave** [comment]
> 
> 
> Fixed with 6.2.11

Not for me, just installed the new version and seafile client still isnt opening. Maybe with a clean install? But installing a new windows helped...

**Comment by der-eismann** [comment]
I just installed the Seafile client at two friend's PCs and they have the same problem... the client won't start unless the seaf-daemon.exe is started separately. They also have problems with SeaDrive and they only use Windows Defender.
Seafile really is a great piece of software, but the support is basically non-existent. Maybe it's time to switch to Nextcloud.

**Comment by Eagle2021** [comment]
I had the same problem with versions later than 6.1.8 on Windows 7. I have Acronis Active Protection running and this caused the problems with Seafile client. When I put the client and daemon to the whitelist in Acronis or disabled Active Protection it works for me.
