### ISSUE TITLE
[Documentation] docker-compose.yml file missing from website documentation

### ISSUE THREAD

**Issue by Taubin** [haiwen/seafile#2402]
Following the installation directions for docker on [your website](https://manual.seafile.com/docker/pro-edition/Deploy%20Seafile-pro%20with%20Docker/) links to a docker-compose.yml file that [does not exist](https://download.seafile.com/d/320e8adf90fa43ad8fee/files/?p=/docker/pro-edition/docker-compose.yml)

This file also does not seem to exist on your github anywhere that I can find. This should be reinstated or the documentation updated to link to the correct file.

**Comment by langhaarschneider** [comment]
seems fixed?

**Comment by Taubin** [comment]
It is in fact fixed now. I'll go ahead and close this. Cheers.

**Comment by adelorenzo** [comment]
Hello,

Unfortunately the problem is back. Can anyone help please?

Thank you.

Rgds,
AD
