### ISSUE TITLE
deleting a local file after adding it to seafile-ignore.txt, should not delete it from the server

### ISSUE THREAD

**Issue by dportabella** [haiwen/seafile#893]
Use case: I want to upload a big file to the server, but once uploaded, I don't want to keep it in my local computer.
I could use the web page to upload the file, but I prefer to simply put the file into my Seafile folder, wait for it to be uploaded and then remove it. Why? because it is convinient: I can easily upload a big file, or a lot of files, shutdown the computer even in the middle of the upload, and Seafile will make sure that it eventually gets to the server (much better than using the web page).

So, I create a file named "video.mpg" in my Seafile folder, and it gets uploaded to the server.
then I add "video.mpg" to seafile-ignore.txt.
then I delete "video.mpg" from my computer (to free some space in my computer)

at this point, Seafile also deletes the "video.mpg" file from the server.
why?
how can I avoid that Seafile deletes this file from the server, once it has been added to seafile-ignore.txt?

**Comment by killing** [comment]
This has been fixed in latest version.

**Comment by dportabella** [comment]
I still have the same issue.
Seafile Client 5.0.6, OSX 10.10.5
Seafile Server 5.0.5
find here a scenario to replicate: https://github.com/haiwen/seafile-client/issues/788

**Comment by dportabella** [comment]
any news on this issue?

**Comment by eperezv** [comment]
I have the same issue. Any news?

**Comment by Kaan88** [comment]
Still happens, seafile ignores the changes but if I delete the folder it's also deleted on the server.

**Comment by liam-k** [comment]
2021 – I’m having the same issue with the macOS client. Excluded folders aren’t tracked in terms of changes but if you delete them on one machine they get deleted on the server and on other synced devices. This ticket should be reopened.

**Comment by dportabella** [comment]
> 2021 – I’m having the same issue with the macOS client. Excluded folders aren’t tracked in terms of changes but if you delete them on one machine they get deleted on the server and on other synced devices. This ticket should be reopened.

I moved to owncloud: https://owncloud.com/get-started/

**Comment by ilka-schulz** [comment]
> This has been fixed in latest version.

I still have this problem with
- Sync Client 9.0.8 (Linux Appimage)
- Server 12.0.14 (Docker)

**Comment by ilka-schulz** [comment]
@killing can you please re-open this issue? It is not fixed.

**Comment by feiniks** [comment]
Hello,

Please check whether this issue still occurs when using the latest version of the seafile client. If it does, please provide detailed steps to reproduce the problem. Additionally, please include the contents of the `seafile-ignore.txt` file.
